/robot1/controller_manager:
  ros__parameters:
    update_rate: 50

    robot1_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot1_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


/robot1/robot1_joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false


/robot1/robot1_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.20
    wheel_radius: 0.032

    odom_frame_id: odom
    base_frame_id: base_footprint

    publish_rate: 50.0
    enable_odom_tf: true
    use_stamped_vel: false
    cmd_vel_timeout: 0.5

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    position_feedback: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.35
        min_velocity: -0.20
        has_acceleration_limits: true
        max_acceleration: 0.8
        min_acceleration: -0.8
        has_jerk_limits: false

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.2
        min_velocity: -1.2
        has_acceleration_limits: true
        max_acceleration: 1.5
        min_acceleration: -1.5
        has_jerk_limits: false


/robot2/controller_manager:
  ros__parameters:
    update_rate: 50

    robot2_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot2_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


/robot2/robot2_joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false


/robot2/robot2_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.20
    wheel_radius: 0.032

    odom_frame_id: odom
    base_frame_id: base_footprint

    publish_rate: 50.0
    enable_odom_tf: true
    use_stamped_vel: false
    cmd_vel_timeout: 0.5

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    position_feedback: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.35
        min_velocity: -0.20
        has_acceleration_limits: true
        max_acceleration: 0.8
        min_acceleration: -0.8
        has_jerk_limits: false

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.2
        min_velocity: -1.2
        has_acceleration_limits: true
        max_acceleration: 1.5
        min_acceleration: -1.5
        has_jerk_limits: false